# -*- coding: utf-8 -*-

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' },, { name: 'Copenhagen' },])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#departement
  Liste.create!([
{quoi: "depart", content: "01-Ain"},
{quoi: "depart", content: "02 - Aisne"},
{quoi: "depart", content: "03 - Allier"},
{quoi: "depart", content: "04 - Alpes-de-Haute-Provence"},
{quoi: "depart", content: "05 - Hautes-Alpes"},
{quoi: "depart", content: "06 - Alpes Maritimes"},
{quoi: "depart", content: "07 - Ardèche"},
{quoi: "depart", content: "08 - Ardennes"},
{quoi: "depart", content: "09 - Ariège"},
{quoi: "depart", content: "10 - Aube"},
{quoi: "depart", content: "11 - Aude"},
{quoi: "depart", content: "12 - Aveyron"},
{quoi: "depart", content: "13 - Bouches"},
{quoi: "depart", content: "14 - Calvados"},
{quoi: "depart", content: "15 - Cantal"},
{quoi: "depart", content: "16 - Charente"},
{quoi: "depart", content: "17 - Charente-Maritime"},
{quoi: "depart", content: "18 - Cher"},
{quoi: "depart", content: "19 - Corrèze"},
{quoi: "depart", content: "2A - Corse-du-Sud"},
{quoi: "depart", content: "2B - Haute Corse"},
{quoi: "depart", content: "21 - Côte-d'Or"},
{quoi: "depart", content: "22 - Côtes d'Armor"},
{quoi: "depart", content: "23 - Creuse"},
{quoi: "depart", content: "24 - Dordogne"},
{quoi: "depart", content: "25 - Doubs"},
{quoi: "depart", content: "26 - Drôme"},
{quoi: "depart", content: "27 - Eure"},
{quoi: "depart", content: "28 - Eure-et-Loir"},
{quoi: "depart", content: "29 - Finistère"},
{quoi: "depart", content: "30 - Gard"},
{quoi: "depart", content: "31 - Haute Garonne"},
{quoi: "depart", content: "32 - Gers"},
{quoi: "depart", content: "33 - Gironde"},
{quoi: "depart", content: "34 - Hérault"},
{quoi: "depart", content: "35 - Ille-et-Vilaine"},
{quoi: "depart", content: "36 - Indre"},
{quoi: "depart", content: "37 - Indre-et-Loire"},
{quoi: "depart", content: "38 - Isère"},
{quoi: "depart", content: "39 - Jura"},
{quoi: "depart", content: "40 - Landes"},
{quoi: "depart", content: "41 - Loir-et-Cher"},
{quoi: "depart", content: "42 - Loire"},
{quoi: "depart", content: "43 - Haute Loire"},
{quoi: "depart", content: "44 - Loire Atlantique"},
{quoi: "depart", content: "45 - Loiret"},
{quoi: "depart", content: "46 - Lot"},
{quoi: "depart", content: "47 - Lot-et-Garonne"},
{quoi: "depart", content: "48 - Lozère"},
{quoi: "depart", content: "49 - Maine-et-Loire"},
{quoi: "depart", content: "50 - Manche"},
{quoi: "depart", content: "51 - Marne"},
{quoi: "depart", content: "52 - Haute Marne"},
{quoi: "depart", content: "53 - Mayenne"},
{quoi: "depart", content: "54 - Meurthe-et-Moselle"},
{quoi: "depart", content: "55 - Meuse"},
{quoi: "depart", content: "56 - Morbihan"},
{quoi: "depart", content: "57 - Moselle"},
{quoi: "depart", content: "58 - Nièvre"},
{quoi: "depart", content: "59 - Nord"},
{quoi: "depart", content: "60 - Oise"},
{quoi: "depart", content: "61 - Orne"},
{quoi: "depart", content: "62 - Pas-de-Calais"},
{quoi: "depart", content: "63 - Puy-de-Dôme"},
{quoi: "depart", content: "64 - Pyrénées Atlantiques"},
{quoi: "depart", content: "65 - Hautes Pyrénées"},
{quoi: "depart", content: "66 - Pyrénées Orientales"},
{quoi: "depart", content: "67 - Bas-Rhin"},
{quoi: "depart", content: "68 - Haut-Rhin"},
{quoi: "depart", content: "69 - Rhône"},
{quoi: "depart", content: "70 - Haute Saône"},
{quoi: "depart", content: "71 - Saône-et-Loire"},
{quoi: "depart", content: "72 - Sarthe"},
{quoi: "depart", content: "73 - Savoie"},
{quoi: "depart", content: "74 - Haute Savoie"},
{quoi: "depart", content: "75 - Paris"},
{quoi: "depart", content: "76 - Seine Maritime"},
{quoi: "depart", content: "77 - Seine-et-Marne"},
{quoi: "depart", content: "78 - Yvelines"},
{quoi: "depart", content: "79 - Deux-Sèvres"},
{quoi: "depart", content: "80 - Somme"},
{quoi: "depart", content: "81 - Tarn"},
{quoi: "depart", content: "82 - Tarn-et-Garonne"},
{quoi: "depart", content: "83 - Var"},
{quoi: "depart", content: "84 - Vaucluse"},
{quoi: "depart", content: "85 - Vendée"},
{quoi: "depart", content: "86 - Vienne"},
{quoi: "depart", content: "87 - Haute Vienne"},
{quoi: "depart", content: "88 - Vosges"},
{quoi: "depart", content: "89 - Yonne"},
{quoi: "depart", content: "90 - Territoire de Belfort"},
{quoi: "depart", content: "91 - Essonne"},
{quoi: "depart", content: "92 - Hauts-de-Seine"},
{quoi: "depart", content: "93 - Seine-St-Denis"},
{quoi: "depart", content: "94 - Val-de-Marne"},
{quoi: "depart", content: "95 - Val-D'Oise"},
{quoi: "depart", content: "971 - Guadeloupe"},
{quoi: "depart", content: "972 - Martinique"},
{quoi: "depart", content: "973 - Guyane"},
{quoi: "depart", content: "974 - La Réunion"},
{quoi: "depart", content: "976 - Mayotte"},
{quoi: "filiere", content: "Tranchées épandage"},
{quoi: "filiere", content: "Tranchées épandage dans la pente"},
{quoi: "filiere", content: "Lit d'épandage'"},
{quoi: "filiere", content: "Filtre à sable vertical"},
{quoi: "filiere", content: "Filtre à sable vertical drainé"},
{quoi: "filiere", content: "Filtre horizontal"},
{quoi: "filiere", content: "Tertre"},
{quoi: "filiere", content: "Tertre dans la pente"},
{quoi: "filiere", content: "Tertre drainé"},
{quoi: "filiere", content: "Filtre "},






]
)
